### ISSUE TITLE
Circuit Connected Accumulator causes "Invalid source circuit connector ID: 0"

### ISSUE THREAD

**Issue by justarandomgeek** [DaveMcW/blueprint-string#4]
When exporting and reimporting a blueprint that contains a circuit connected Accumulator, I always get this error. I can't seem to track it down myself. 

https://i.imgur.com/72mGNzx.png shows the simplest structure I've found so far to exhibit this behavior.

**Comment by DaveMcW** [comment]
Escalated to Factorio bug: https://forums.factorio.com/viewtopic.php?f=7&t=29793
